### ISSUE TITLE
Issue with 83 List_of_RNA_structure_prediction_software

### ISSUE THREAD

**Issue by philsMINT** [ag-gipp/GoUldI#36]
is the tree correct like this?
[Link to List_of_RNA_structure_prediction_software, qID 83](https://gouldi.wmflabs.org/83)

**Comment by AndreG-P** [comment]
In another case we had 10 equations in one formula and picked just one randomly. To be consistent, we should do the same here. Just pick one relation and delete the other. (keep the original input TeX the same)
