### ISSUE TITLE
Issue with 278 Use of Lagrange multipliers Context 2

### ISSUE THREAD

**Issue by philsMINT** [ag-gipp/GoUldI#55]
set of tensors?
[Link to Use of Lagrange multipliers Context 2, qID 278](https://gouldi.wmflabs.org/278)

**Comment by AndreG-P** [comment]
Is it a single expression or a list of two? If it's a list, just pick one randomly (see other list cases with multiple equations or relations). 
If it is a single expression, create a new macro to describe the parent node,probably the comma?
