### ISSUE TITLE
Create a project overview page

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/GoUldI#58]
Create project overview page describing the purpose of the repo and links to the cases.
I suggest to use [marked](https://www.npmjs.com/package/marked) to show the page on the main page.

**Comment by philsMINT** [comment]
what is meant by "links to the cases"?

**Comment by AndreG-P** [comment]
Can be closed once the bug in #62 is solved!

**Comment by AndreG-P** [comment]
Solved with: adc301a8e269369700f4e4aec2c53d094bda375f
