### ISSUE TITLE
VMEXT popup for wikidata broken

### ISSUE THREAD

**Issue by AndreG-P** [ag-gipp/GoUldI#62]
@physikerwelt 
I just included the `/about` page with the rendered markdown README.md as start page.
To make it the start-page, I needed to move the gouldi-pages to a subpath. I called the subpath `gold`.

Everything works now. For example calling `gouldi.wmflabs.org/gold/5` will load QID: 5.
However, this subpath `gold` destroys the popup info box of VMEXT. It tries to fetch data from wikidata but fails. I don't know why.

See my changes: 7e7936467c53727ea5ca200c6f2e6fde4f406ee1

**Comment by physikerwelt** [comment]
I don't see the about page. And I'm happy that the /\d pages are not broken. This would not be acceptable.

**Comment by AndreG-P** [comment]
The deploy system was broken again... it turned out, the server was 31 commits behind...
However, fixed the issue.

Just to explain in a more detailed way. The URL is still:
`gouldi.wmflabs.org`
Every path that doesn't match a file or `gold` will redirected to the about page. That includes the `/` path.
The "old" gouldi can be called by the subpath `gold/`. Note that the last slash is mandatory, otherwise you will just see the `/node_modules/vmext/public/favicon.ico`
Thereby, all qID pages also need the prefix `gold/` path:
```
https://gouldi.wmflabs.org         --> redirect to: https://gouldi.wmflabs.org/about
https://gouldi.wmflabs.org/test    --> redirect to: https://gouldi.wmflabs.org/about
https://gouldi.wmflabs.org/gold    --> redirect to: math-search icon, don't know why...
https://gouldi.wmflabs.org/gold/   --> redirect to: old gouldi website (GoUldI)
https://gouldi.wmflabs.org/gold/:qID -> redirects to specific qID.
```

As mentioned before, the vmext-popup cannot fetch the data from wikidata. I think the reason is, that something in `vmext/routes/routes.js` cannot handle the new subpath `gold/`. See other necessary path changes in
https://github.com/ag-gipp/GoUldI/blob/7e7936467c53727ea5ca200c6f2e6fde4f406ee1/gouldi.js#L50-L59

**Comment by AndreG-P** [comment]
adc301a8e269369700f4e4aec2c53d094bda375f
