### ISSUE TITLE
Deploy Update doesn't work

### ISSUE THREAD

**Issue by AndreG-P** [ag-gipp/GoUldI#7]
@physikerwelt 
Das deploy update geht noch nicht. Ich hab Änderungen gepusht und cgi-bin/deploy.sh aufgerufen. Das hat auch wunderbar geklappt und die Änderungen sind (wenn ich gouldi-deploy.wmflabs.org aufrufe) auch zu sehen.
**Aber** wenn ich mich bei drmf-beta anmelde und in /srv/gouldi/source nachschaue, sind dort die Änderungen **nicht** gepullt! Trotzdem wird noch immer von hier der server gestartet.

Sieht so aus als gäbe es jetzt 2 gouldi auf drmf-beta. Die eine wird geupdated, die andere nicht...

**Comment by physikerwelt** [comment]
works now
